### ISSUE TITLE
https://reddit.com/r/onions Failed - Can't Spider

### ISSUE THREAD

**Issue by tomtom87** [Bl-nK/torSpider#2]
Tried to run the example and get the following error

```
https://reddit.com/r/onions Failed - Can't Spider
```

Any ideas?

**Comment by Bl-nK** [comment]
Can you pull the latest code and try again? I made that error more verbose. It might give us an idea as to what happened.

**Comment by Bl-nK** [comment]
Adding on, I tried and got the following output with the new code.

```
https://reddit.com/r/onions Failed - Can't Spider - java.io.IOException: Server returned HTTP response code: 429 for URL: https://www.reddit.com/r/onions
```

429 stands for too many requests. This is on the Reddit side of things. Let me know if you have a different error please.

**Comment by tomtom87** [comment]
Tried the new code, new error now: 

```
 groovy onionFinder.groovy https://reddit.com/r/onions
https://reddit.com/r/onions Failed - Can't Spider - java.net.SocketException: Can't connect to SOCKS proxy:Connection refused
```

**Comment by tomtom87** [comment]
Oh it assumes I run a proxy on localhost now? 

```
System.properties.putAll( ["proxySet":"true","socksProxyHost":"localhost", "socksProxyPort":"9050"] )
```

**Comment by Bl-nK** [comment]
Yes, it requires that you are running Tor on your local system. Tor provides a SOCKS proxy that you can use to send data through Tor.
